### ISSUE TITLE
Select a framework for the web app

### ISSUE THREAD

**Issue by dmleach** [dmleach/recroot#8]
We need a Javascript framework to build the web app in. Angular? Vue? Ember?

**Comment by dmleach** [comment]
@MiscCurt Read up on Angular, React, and Ember. Of those Angular and Ember made more sense to her. Angular is built more for single page apps, Ember for multi-page apps

Dave barely managed to get Angular up and running in time for today's call

**Comment by dmleach** [comment]
@bpeace71 is aware of React and has used it a little

**Comment by dmleach** [comment]
If @MiscCurt had to pick one (and I made her), she'd pick React

**Comment by MiscCurt** [comment]
I know we closed this one but knew of my Twitter follows posted this and based on this I'd still probably go with React but perhaps would have taken a look at Vue as well.

https://twitter.com/scotch_io/status/973948719262523392?s=21
